archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    main: ./cmd/gcp-artifact-registry-docker-proxy/main.go

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge pull request"
      - "^Release"
  sort: asc
  use: github

dockers:
  - build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
    image_templates:
      - "ghcr.io/persona-id/{{.ProjectName}}:{{ .Tag }}-amd64"
    goarch: amd64
    skip_push: false
    use: buildx
  - build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
    image_templates:
      - "ghcr.io/persona-id/{{.ProjectName}}:{{ .Tag }}-arm64v8"
    goarch: arm64
    skip_push: false
    use: buildx

docker_manifests:
  - image_templates:
      - "ghcr.io/persona-id/{{.ProjectName}}:{{ .Tag }}-amd64"
      - "ghcr.io/persona-id/{{.ProjectName}}:{{ .Tag }}-arm64v8"
    name_template: "ghcr.io/persona-id/{{.ProjectName}}:{{ .Tag }}"
    skip_push: false
  - image_templates:
      - "ghcr.io/persona-id/{{.ProjectName}}:{{ .Tag }}-amd64"
      - "ghcr.io/persona-id/{{.ProjectName}}:{{ .Tag }}-arm64v8"
    name_template: "ghcr.io/persona-id/{{.ProjectName}}:latest"
    skip_push: false

project_name: gcp-artifact-registry-docker-proxy
