name: "Run Tests"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
      with:
        go-version-file: go.mod

    - name: Vet
      run: go vet ./...

    - env:
        GOOGLE_APPLICATION_CREDENTIALS_CONTENTS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_CONTENTS }}
      name: Test
      run: go test -v ./...
